/**
 * The people a traveller can hire at their destination.
 *
 * The portraits in `public/images/pros` are **stock photographs standing in
 * for the real professionals** — Unsplash models, cast to match each listing.
 * They are placeholders for design, exactly like the names and the rates.
 * Before this page lists anyone genuinely bookable, replace the file with a
 * photograph of that person, taken or supplied with their consent. Never leave
 * a stranger's face attached to a real, chargeable listing.
 *
 * `photo` is optional; `ProAvatar` falls back to a monogram tile without one.
 */

export const professions = [
  "photographer",
  "videographer",
  "chef",
  "barber",
  "shopper",
  "interpreter",
  "security",
  "childcare",
  "event",
  "freelancer",
] as const;

export type Profession = (typeof professions)[number];

export const professionLabels: Record<Profession, string> = {
  photographer: "Photographer",
  videographer: "Videographer",
  chef: "Private chef / cook",
  barber: "Barber / stylist",
  shopper: "Personal shopper",
  interpreter: "Interpreter / translator",
  security: "Private security",
  childcare: "Babysitter / nanny",
  event: "Event planner",
  freelancer: "Freelancer / other",
};

export type Professional = {
  id: string;
  name: string;
  tagline: string;
  profession: Profession;
  city: string;
  country: string;
  languages: string[];
  rating: number;
  jobs: number;
  years: number;
  /** Headline rate. `unit` is what the price buys. */
  price: number;
  unit: string;
  about: string;
  availability: string;
  packages: { name: string; description: string; price: number }[];
  included: string[];
  skills: string[];
  cancellation: string;
  verified: boolean;
  /** Optional real portrait; the monogram tile is used when absent. */
  photo?: string;
};

export const professionals: Professional[] = [
  {
    id: "elena-marousi",
    photo: "/images/pros/elena-marousi.jpg",
    name: "Elena Marousi",
    tagline: "Caldera & golden-hour portrait photographer",
    profession: "photographer",
    city: "Santorini",
    country: "Greece",
    languages: ["English", "Greek"],
    rating: 4.9,
    jobs: 240,
    years: 9,
    price: 280,
    unit: "per 2-hour shoot",
    about:
      "Shoots the caldera almost every evening and knows which terraces catch the last light. Relaxed direction — you walk, she photographs, nobody has to pose.",
    availability: "Golden hour daily, mornings on request",
    packages: [
      { name: "Golden hour", description: "2 hours, Oia to Imerovigli", price: 280 },
      { name: "Half day", description: "4 hours, two villages", price: 520 },
      {
        name: "Proposal cover",
        description: "Discreet, then a proper shoot",
        price: 640,
      },
    ],
    included: [
      "60 edited photos",
      "Online gallery",
      "Route planning",
      "Weather backup date",
    ],
    skills: ["Portrait", "Golden hour", "Couples", "Proposal"],
    cancellation: "Free up to 48h before",
    verified: true,
  },
  {
    id: "kenji-watanabe",
    photo: "/images/pros/kenji-watanabe.jpg",
    name: "Kenji Watanabe",
    tagline: "Neon street & documentary photographer",
    profession: "photographer",
    city: "Tokyo",
    country: "Japan",
    languages: ["Japanese", "English"],
    rating: 4.8,
    jobs: 310,
    years: 15,
    price: 240,
    unit: "per 2-hour walk",
    about:
      "Former magazine photojournalist who now walks visitors through Shinjuku and Shibuya after dark. Documentary style — no stiff posing, just your trip as it actually happened.",
    availability: "Evenings, and weekends all day",
    packages: [
      {
        name: "Neon night walk",
        description: "2 hours, Shinjuku to Golden Gai",
        price: 240,
      },
      { name: "Two-district day", description: "4 hours, day and night", price: 430 },
      { name: "Film only", description: "Analogue roll, hand scanned", price: 300 },
    ],
    included: [
      "35mm + digital",
      "30 edited photos",
      "Route planning",
      "Rain backup plan",
    ],
    skills: ["Street", "Night", "Documentary", "Film"],
    cancellation: "Free up to 48h before",
    verified: true,
  },
  {
    id: "putu-ardana",
    photo: "/images/pros/putu-ardana.jpg",
    name: "Putu Ardana",
    tagline: "Cinematic travel film-maker",
    profession: "videographer",
    city: "Bali",
    country: "Indonesia",
    languages: ["Indonesian", "English"],
    rating: 4.9,
    jobs: 180,
    years: 7,
    price: 390,
    unit: "per half day",
    about:
      "Cuts short travel films with a drone and a gimbal, usually delivered before you have flown home. Works fast and knows which rice terraces are quiet at sunrise.",
    availability: "Sunrise and sunset slots, book two days ahead",
    packages: [
      { name: "Half day", description: "4 hours, one 90-second film", price: 390 },
      { name: "Full day", description: "8 hours, film plus reels", price: 690 },
      { name: "Reels pack", description: "Six vertical cuts for social", price: 260 },
    ],
    included: ["Drone footage", "Colour grading", "Licensed music", "48-hour delivery"],
    skills: ["Drone", "Gimbal", "Colour grade", "Short film"],
    cancellation: "Free up to 72h before",
    verified: true,
  },
  {
    id: "marina-castro",
    photo: "/images/pros/marina-castro.jpg",
    name: "Marina Castro",
    tagline: "Event & lifestyle videographer",
    profession: "videographer",
    city: "Rio de Janeiro",
    country: "Brazil",
    languages: ["Portuguese", "English", "Spanish"],
    rating: 4.8,
    jobs: 145,
    years: 8,
    price: 340,
    unit: "per half day",
    about:
      "Covers birthdays, launches and family trips across Rio. Two cameras, discreet, and used to filming where the light is difficult.",
    availability: "Most days, weekends fill early",
    packages: [
      { name: "Half day", description: "4 hours, one edited film", price: 340 },
      { name: "Full event", description: "8 hours, two cameras", price: 620 },
    ],
    included: [
      "Two cameras",
      "Wireless audio",
      "Edited film",
      "Raw footage on request",
    ],
    skills: ["Events", "Interviews", "Lifestyle", "Audio"],
    cancellation: "Free up to 72h before",
    verified: true,
  },
  {
    id: "hicham-benali",
    photo: "/images/pros/hicham-benali.jpg",
    name: "Hicham Benali",
    tagline: "Private chef — Moroccan home cooking",
    profession: "chef",
    city: "Marrakech",
    country: "Morocco",
    languages: ["Arabic", "French", "English"],
    rating: 5,
    jobs: 210,
    years: 12,
    price: 160,
    unit: "per dinner (up to 6)",
    about:
      "Cooks the food he grew up on, in your riad kitchen. Shops the souk that morning, cooks in the evening, and leaves the kitchen cleaner than he found it.",
    availability: "Evenings, six days a week",
    packages: [
      {
        name: "Dinner for six",
        description: "Four courses, market shopping included",
        price: 160,
      },
      { name: "Feast for twelve", description: "Six courses, two helpers", price: 380 },
      { name: "Souk & cook", description: "Morning market, then a lesson", price: 240 },
    ],
    included: ["Market shopping", "All ingredients", "Service", "Kitchen left clean"],
    skills: ["Tagine", "Couscous", "Pastilla", "Vegetarian"],
    cancellation: "Free up to 24h before",
    verified: true,
  },
  {
    id: "thandi-mokoena",
    photo: "/images/pros/thandi-mokoena.jpg",
    name: "Thandi Mokoena",
    tagline: "Private chef — braai, seafood & plant-based",
    profession: "chef",
    city: "Cape Town",
    country: "South Africa",
    languages: ["English", "Xhosa", "Afrikaans"],
    rating: 4.9,
    jobs: 165,
    years: 10,
    price: 190,
    unit: "per dinner (up to 8)",
    about:
      "Runs a supper club in Woodstock and cooks privately around the Cape. Strong on seafood and genuinely good at plant-based, not just an afterthought menu.",
    availability: "Thursday to Sunday",
    packages: [
      {
        name: "Dinner for eight",
        description: "Three courses, your kitchen",
        price: 190,
      },
      { name: "Braai afternoon", description: "Long lunch, fire-led", price: 260 },
    ],
    included: ["Menu planning", "All ingredients", "Service", "Dietary swaps"],
    skills: ["Seafood", "Braai", "Plant-based", "Wine pairing"],
    cancellation: "Free up to 24h before",
    verified: true,
  },
  {
    id: "sho-nakamura",
    photo: "/images/pros/sho-nakamura.jpg",
    name: "Sho Nakamura",
    tagline: "Hotel-visit barber — fades & hot-towel shaves",
    profession: "barber",
    city: "Tokyo",
    country: "Japan",
    languages: ["Japanese", "English"],
    rating: 4.9,
    jobs: 420,
    years: 11,
    price: 70,
    unit: "per cut",
    about:
      "Comes to your hotel with everything, including a chair. Traditional hot-towel shave if you want it, and quick enough to fit before a dinner.",
    availability: "Daily, 8am to 9pm",
    packages: [
      { name: "Cut", description: "Consultation and finish", price: 70 },
      { name: "Cut & shave", description: "Hot towel, traditional razor", price: 110 },
    ],
    included: ["Travel to your hotel", "All equipment", "Products", "Clean-up"],
    skills: ["Fades", "Scissor cut", "Beard", "Hot towel"],
    cancellation: "Free up to 12h before",
    verified: true,
  },
  {
    id: "naledi-dube",
    photo: "/images/pros/naledi-dube.jpg",
    name: "Naledi Dube",
    tagline: "Mobile stylist — braids, locs & blowouts",
    profession: "barber",
    city: "Cape Town",
    country: "South Africa",
    languages: ["English", "Zulu"],
    rating: 4.8,
    jobs: 290,
    years: 9,
    price: 95,
    unit: "per session",
    about:
      "Travels to you with a full kit. Specialises in protective styles and knows how to work with hair that has just been through a long flight.",
    availability: "Daily by appointment",
    packages: [
      { name: "Blowout & style", description: "Wash, treat, finish", price: 95 },
      { name: "Braids", description: "Half day, protective style", price: 180 },
    ],
    included: ["Travel to you", "Products", "Consultation", "Aftercare notes"],
    skills: ["Braids", "Locs", "Blowout", "Natural hair"],
    cancellation: "Free up to 24h before",
    verified: true,
  },
  {
    id: "yasmine-el-fassi",
    photo: "/images/pros/yasmine-el-fassi.jpg",
    name: "Yasmine El Fassi",
    tagline: "Personal shopper — souks, rugs & tailoring",
    profession: "shopper",
    city: "Marrakech",
    country: "Morocco",
    languages: ["Arabic", "French", "English"],
    rating: 5,
    jobs: 130,
    years: 6,
    price: 130,
    unit: "per half day",
    about:
      "Knows which workshops are the real thing and what a rug should actually cost. Negotiates in Darija so you do not pay the visitor price.",
    availability: "Mornings and afternoons, closed Fridays",
    packages: [
      { name: "Half day", description: "4 hours, one quarter", price: 130 },
      {
        name: "Full day",
        description: "Souks plus workshops outside the medina",
        price: 230,
      },
      { name: "Rug hunt", description: "Dealers only, shipping arranged", price: 190 },
    ],
    included: ["Negotiation", "Shipping advice", "Quality checks", "Tea, obviously"],
    skills: ["Rugs", "Ceramics", "Tailoring", "Negotiation"],
    cancellation: "Free up to 48h before",
    verified: true,
  },
  {
    id: "aya-kobayashi",
    photo: "/images/pros/aya-kobayashi.jpg",
    name: "Aya Kobayashi",
    tagline: "Personal shopper — vintage, denim & sneakers",
    profession: "shopper",
    city: "Tokyo",
    country: "Japan",
    languages: ["Japanese", "English"],
    rating: 4.9,
    jobs: 175,
    years: 7,
    price: 150,
    unit: "per half day",
    about:
      "Shops Shimokitazawa and Koenji weekly and knows which floors are worth your time. Good at sizing, which is where most visitors come unstuck.",
    availability: "Weekdays, some Saturdays",
    packages: [
      { name: "Half day", description: "4 hours, two neighbourhoods", price: 150 },
      { name: "Full day", description: "Vintage plus department stores", price: 270 },
    ],
    included: [
      "Sizing help",
      "Tax-free paperwork",
      "Shipping advice",
      "Route planning",
    ],
    skills: ["Vintage", "Denim", "Sneakers", "Tax-free"],
    cancellation: "Free up to 48h before",
    verified: true,
  },
  {
    id: "hiroko-tanabe",
    photo: "/images/pros/hiroko-tanabe.jpg",
    name: "Hiroko Tanabe",
    tagline: "Business interpreter — JP/EN, certified",
    profession: "interpreter",
    city: "Tokyo",
    country: "Japan",
    languages: ["Japanese", "English", "Korean"],
    rating: 5,
    jobs: 380,
    years: 18,
    price: 320,
    unit: "per half day",
    about:
      "Eighteen years of boardrooms and factory floors. Consecutive and whispered simultaneous, and will brief you on the etiquette before you walk in.",
    availability: "Weekdays, book a week ahead",
    packages: [
      { name: "Half day", description: "Up to 4 hours", price: 320 },
      { name: "Full day", description: "Up to 8 hours", price: 580 },
      {
        name: "Document review",
        description: "Contract or deck, per 1000 words",
        price: 140,
      },
    ],
    included: [
      "Pre-meeting brief",
      "Glossary prep",
      "Etiquette notes",
      "Written summary",
    ],
    skills: ["Consecutive", "Whispered", "Legal", "Manufacturing"],
    cancellation: "Free up to 72h before",
    verified: true,
  },
  {
    id: "rafael-duarte",
    photo: "/images/pros/rafael-duarte.jpg",
    name: "Rafael Duarte",
    tagline: "Interpreter & fixer — PT/EN/ES",
    profession: "interpreter",
    city: "Rio de Janeiro",
    country: "Brazil",
    languages: ["Portuguese", "English", "Spanish"],
    rating: 4.8,
    jobs: 220,
    years: 10,
    price: 210,
    unit: "per half day",
    about:
      "Half interpreter, half fixer. Handles meetings, but also the bank, the phone shop and whatever else the day turns into.",
    availability: "Most days, short notice possible",
    packages: [
      { name: "Half day", description: "Up to 4 hours", price: 210 },
      { name: "Full day", description: "Up to 8 hours", price: 380 },
    ],
    included: [
      "Interpreting",
      "Local errands",
      "Transport arranged",
      "Phone support after",
    ],
    skills: ["Business", "Medical", "Fixer work", "Short notice"],
    cancellation: "Free up to 48h before",
    verified: true,
  },
  {
    id: "bruno-ferreira",
    photo: "/images/pros/bruno-ferreira.jpg",
    name: "Bruno Ferreira",
    tagline: "Licensed close protection officer",
    profession: "security",
    city: "Rio de Janeiro",
    country: "Brazil",
    languages: ["Portuguese", "English"],
    rating: 4.9,
    jobs: 160,
    years: 14,
    price: 420,
    unit: "per day",
    about:
      "Fourteen years in close protection, licensed and insured. Low profile by preference — the aim is that nobody notices he is there.",
    availability: "Daily, 24-hour cover on request",
    packages: [
      { name: "Day cover", description: "12 hours, one officer", price: 420 },
      { name: "Full cover", description: "24 hours, two officers", price: 900 },
      { name: "Airport transfer", description: "Meet and escort", price: 180 },
    ],
    included: [
      "Licensed and insured",
      "Route recce",
      "Radio comms",
      "Written risk note",
    ],
    skills: ["Close protection", "Route planning", "Advance recce", "Discreet"],
    cancellation: "Free up to 72h before",
    verified: true,
  },
  {
    id: "sipho-ndlovu",
    photo: "/images/pros/sipho-ndlovu.jpg",
    name: "Sipho Ndlovu",
    tagline: "Security driver & personal escort",
    profession: "security",
    city: "Cape Town",
    country: "South Africa",
    languages: ["English", "Xhosa", "Afrikaans"],
    rating: 4.8,
    jobs: 195,
    years: 11,
    price: 360,
    unit: "per day incl. vehicle",
    about:
      "Driver first, escort second. Knows which routes to avoid after dark and will wait rather than have you stand on a pavement looking for a car.",
    availability: "Daily, early starts fine",
    packages: [
      { name: "Day with vehicle", description: "12 hours, driver and car", price: 360 },
      { name: "Airport run", description: "Meet, escort, transfer", price: 140 },
    ],
    included: [
      "Vehicle and fuel",
      "Licensed driver",
      "Route planning",
      "On-call number",
    ],
    skills: ["Defensive driving", "Escort", "Local routes", "Airport"],
    cancellation: "Free up to 48h before",
    verified: true,
  },
  {
    id: "sofia-papadaki",
    photo: "/images/pros/sofia-papadaki.jpg",
    name: "Sofia Papadaki",
    tagline: "Vetted nanny — infants to school age",
    profession: "childcare",
    city: "Santorini",
    country: "Greece",
    languages: ["Greek", "English"],
    rating: 5,
    jobs: 260,
    years: 13,
    price: 22,
    unit: "per hour",
    about:
      "Paediatric first aid certified, background checked, and has looked after more holiday toddlers than she can count. Brings activities, not a phone.",
    availability: "Days and evenings, minimum three hours",
    packages: [
      { name: "Hourly", description: "Minimum three hours", price: 22 },
      { name: "Evening sitting", description: "6pm to midnight", price: 120 },
      { name: "Full day", description: "8 hours, activities included", price: 160 },
    ],
    included: [
      "Background checked",
      "Paediatric first aid",
      "Activities",
      "Written day notes",
    ],
    skills: ["Infants", "Toddlers", "School age", "First aid"],
    cancellation: "Free up to 24h before",
    verified: true,
  },
  {
    id: "kadek-sari",
    photo: "/images/pros/kadek-sari.jpg",
    name: "Kadek Sari",
    tagline: "Villa nanny & kids' activity host",
    profession: "childcare",
    city: "Bali",
    country: "Indonesia",
    languages: ["Indonesian", "English"],
    rating: 4.9,
    jobs: 310,
    years: 8,
    price: 14,
    unit: "per hour",
    about:
      "Works villa stays across Canggu and Ubud. Water-confident, first aid trained, and very good at wearing children out before dinner.",
    availability: "Daily, minimum four hours",
    packages: [
      { name: "Hourly", description: "Minimum four hours", price: 14 },
      { name: "Full day", description: "8 hours with activities", price: 100 },
    ],
    included: ["First aid trained", "Pool supervision", "Activities", "Meal help"],
    skills: ["Villa stays", "Water safety", "Toddlers", "Activities"],
    cancellation: "Free up to 24h before",
    verified: true,
  },
  {
    id: "dimitra-kalogeri",
    photo: "/images/pros/dimitra-kalogeri.jpg",
    name: "Dimitra Kalogeri",
    tagline: "Proposal & micro-wedding planner",
    profession: "event",
    city: "Santorini",
    country: "Greece",
    languages: ["Greek", "English", "Italian"],
    rating: 5,
    jobs: 140,
    years: 12,
    price: 850,
    unit: "per event",
    about:
      "Plans small ceremonies and proposals on the caldera. Handles the permits, the florist and the part where you have to be somewhere at exactly the right minute.",
    availability: "April to October, books months ahead",
    packages: [
      {
        name: "Proposal",
        description: "Setup, timing, photographer liaison",
        price: 850,
      },
      {
        name: "Micro-wedding",
        description: "Up to 20 guests, full coordination",
        price: 2400,
      },
    ],
    included: ["Permits", "Vendor booking", "On-the-day coordination", "Backup plan"],
    skills: ["Proposals", "Micro-weddings", "Permits", "Vendors"],
    cancellation: "Deposit non-refundable inside 30 days",
    verified: true,
  },
  {
    id: "omar-chraibi",
    photo: "/images/pros/omar-chraibi.jpg",
    name: "Omar Chraibi",
    tagline: "Riad party & desert event producer",
    profession: "event",
    city: "Marrakech",
    country: "Morocco",
    languages: ["Arabic", "French", "English"],
    rating: 4.8,
    jobs: 120,
    years: 9,
    price: 700,
    unit: "per event",
    about:
      "Produces riad dinners and desert camps — musicians, lighting, catering and the logistics of getting forty people an hour out of the city and back.",
    availability: "Year round, peak season books early",
    packages: [
      {
        name: "Riad dinner",
        description: "Up to 30 guests, music and catering",
        price: 700,
      },
      {
        name: "Desert camp",
        description: "Overnight, transport included",
        price: 2100,
      },
    ],
    included: ["Vendor booking", "Transport", "Lighting and sound", "On-site producer"],
    skills: ["Riad events", "Desert camps", "Music", "Catering"],
    cancellation: "Deposit non-refundable inside 21 days",
    verified: true,
  },
  {
    id: "wayan-surya",
    photo: "/images/pros/wayan-surya.jpg",
    name: "Wayan Surya",
    tagline: "Trip fixer, driver & general assistant",
    profession: "freelancer",
    city: "Bali",
    country: "Indonesia",
    languages: ["Indonesian", "English"],
    rating: 4.9,
    jobs: 340,
    years: 10,
    price: 90,
    unit: "per day",
    about:
      "The person you call when something needs sorting. Drives, translates, queues, finds the pharmacy, and knows which temple is quiet on a Tuesday.",
    availability: "Daily, short notice usually fine",
    packages: [
      { name: "Day with car", description: "10 hours, driver and vehicle", price: 90 },
      { name: "Half day", description: "5 hours", price: 55 },
    ],
    included: ["Vehicle and fuel", "Translation", "Errands", "Local know-how"],
    skills: ["Driving", "Fixer work", "Translation", "Errands"],
    cancellation: "Free up to 12h before",
    verified: true,
  },
  {
    id: "lerato-khumalo",
    photo: "/images/pros/lerato-khumalo.jpg",
    name: "Lerato Khumalo",
    tagline: "Remote-work assistant & city fixer",
    profession: "freelancer",
    city: "Cape Town",
    country: "South Africa",
    languages: ["English", "Sotho"],
    rating: 4.8,
    jobs: 150,
    years: 6,
    price: 110,
    unit: "per day",
    about:
      "Sets up your week if you are working from here: SIM card, a desk that actually has power, and someone to handle the admin while you are in meetings.",
    availability: "Weekdays",
    packages: [
      { name: "Day rate", description: "8 hours, admin and errands", price: 110 },
      { name: "Setup week", description: "SIM, banking help, workspace", price: 420 },
    ],
    included: [
      "SIM and data",
      "Workspace booking",
      "Admin and errands",
      "Local contacts",
    ],
    skills: ["Admin", "Workspace", "Errands", "Local setup"],
    cancellation: "Free up to 24h before",
    verified: true,
  },
];

/** Every city with at least one professional, alphabetised. */
export const professionalCities = [...new Set(professionals.map((p) => p.city))].sort();
